services:
  ros2_time_sync:
    build:
      context: ..
      dockerfile: runtime/Dockerfile
    image: ros2_time_sync_runtime:latest
    container_name: ros2_time_sync_runtime
    privileged: true # Allows access to devices
    volumes:
      - /dev:/dev:rw # Mounts the device directory to allow access to devices
    environment:
      RCUTILS_COLORIZED_OUTPUT: 1 # Allows launch files to print colored text
    stdin_open: true # Keeps the container running even if it's not attached to a terminal. 
    tty: true # outuputs the terminal for the container, allowing you to interact with it.
    network_mode: host # Uses the host's network stack, which is useful for ROS
    restart: always
    entrypoint: ["/entrypoint.sh"]
    